### ISSUE TITLE
希望添加一个照片栏

### ISSUE THREAD

**Issue by pawn-sxy** [FesianXu/Potato-CV#1]
将姓名和联系方式等信息设置成左对齐，然后在右上角添加一个照片栏

**Comment by FesianXu** [comment]
@pawn-sxy 那你可能会比较喜欢这个
https://github.com/huajh/awesome-latex-cv
我的简历模版是根据他做了很多简化的，因为我觉得很多元素太过冗余，在投简历过程中很容易给人一个找不到重点的感觉（我这半年投了蛮多公司得出的结论），因此我这个简历模版的用户定位是程序员，而且是喜欢简洁风的程序员。哈哈哈哈哈哈

**Comment by FesianXu** [comment]
@pawn-sxy 这个大概就是直男审美风的CV了？？哈哈哈哈
